[general]
import= [
    "themes/catppuccin_macchiato.toml"
]

[env]
term = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

[font]
size = 12
normal.family = "FantasqueSansM Nerd Font Mono"

[keyboard]
bindings = [
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
]
